name: Docker
run-name: Push and Build Docker Images to Docker Hub 🐋

# Later could also push images to GitHub Container Registry (GHCR).

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    name: "Build (${{ matrix.component }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        component: [backend, frontend]

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Checkout repository code.
        uses: actions/checkout@v4

      # Setup QEMU (needed for build-push-action).
      - name: Set up QEMU.
        uses: docker/setup-qemu-action@v3

      # Setup docker buildx (needed for build-push-action).
      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v3

      # Login to docker hub.
      - name: Login to Docker Hub.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds and pushes docker images to docker hub.
      - name: Build and push Docker Image.
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.component }}
          file: ${{ matrix.component }}/Dockerfile
          platforms: linux/amd64  # or add linux/arm64 for multi-platform.
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/interex-${{ matrix.component }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/interex-${{ matrix.component }}:${{ github.sha }}
